# URLs from which to download XTRA data (Wajib Nyala untuk A-GPS)
XTRA_SERVER_1=https://xtrapath1.izatcloud.net/xtra2.bin
XTRA_SERVER_2=http://xtrapath2.izatcloud.net/xtra2.bin
XTRA_SERVER_3=http://xtrapath3.izatcloud.net/xtra2.bin

# Version check for XTRA
XTRA_VERSION_CHECK=1
ERR_ESTIMATE=0

# NTP server (Google sangat stabil)
NTP_SERVER=time.google.com

# XTRA CA path
XTRA_CA_PATH=/system/etc/security/cacerts

# DEBUG LEVELS: 0 - none, 1 - Error, 2 - Warning, 3 - Info
DEBUG_LEVEL=2

# Intermediate position report (1=enable) Bikin GPS terasa lebih responsif saat awal buka Maps
INTERMEDIATE_POS=1

# supl version 2.0 (Lebih modern dan akurat)
SUPL_VER=0x20000
SUPL_ES=1
USE_EMERGENCY_PDN_FOR_EMERGENCY_SUPL=0

# SUPL_MODE 3 = MSA (Mobile Station Assisted) & MSB (Mobile Station Based)
SUPL_MODE=3

# GPS Capabilities bit mask
CAPABILITIES=0x37

################################
##### AGPS server settings #####
################################
# Gunakan Server Google, jangan pakai server Cina (qxwz)
SUPL_HOST=supl.google.com
SUPL_PORT=7275

####################################
#  LTE Positioning Profile Settings
####################################
LPP_PROFILE=2

################################
# EXTRA SETTINGS
################################
# NMEA provider 1 = Kalkulasi diserahkan langsung ke Modem Snapdragon (Sangat Cepat)
NMEA_PROVIDER=1
SGLTE_TARGET=0

##################################################
# Select Positioning Protocol on A-GLONASS system
##################################################
A_GLONASS_POS_PROTOCOL_SELECT=15
